### ISSUE TITLE
Halstead complexity not being calculated for async functions

### ISSUE THREAD

**Issue by rharish101** [rubik/radon#187]
When using Radon's CLI for the Halstead measures with the `-f` flag, they aren't being calculated for asynchronous functions. On the other hand, it is working for cyclomatic complexity.

Here's a code snippet for testing:
```python
async def foo():
    pass

def bar():
    pass
```

This is Radon's output for `radon hal -f test.py`:
```
test.py:
    bar:
        h1: 0
        h2: 0
        N1: 0
        N2: 0
        vocabulary: 0
        length: 0
        calculated_length: 0
        volume: 0
        difficulty: 0
        effort: 0
        time: 0.0
        bugs: 0.0
```

This is Radon's output for `radon cc test.py`:
```
test.py
    F 1:0 foo - A
    F 4:0 bar - A
```

I am using Python 3.8, with Radon 4.1.0 on Arch Linux. I have installed Radon from [the AUR](https://aur.archlinux.org/packages/python-radon/).
