### ISSUE TITLE
[feature] Add support for pre-commit

### ISSUE THREAD

**Issue by Freed-Wu** [rubik/radon#225]
<https://pre-commit.com/>

**Comment by rubik** [comment]
@Freed-Wu What would this support entail? From a quick read it would seem all configuration is created in each repository where pre-commit is installed.

**Comment by Freed-Wu** [comment]
Hey, sorry for late.

Just add a `.pre-commit-config.yaml` in the root directory of the repository is OK. Like <https://github.com/PyCQA/doc8>.

**Comment by rubik** [comment]
@tzmara @Freed-Wu In that case, since the exit code is important, [xenon](https://github.com/rubik/xenon) is the program to use. Radon is meant for human use, Xenon is for programmatic use. It already has a pre-commit hook. You can configure it to fail when specific thresholds are surpassed.

**Comment by izikeros** [comment]
Here is a snippet to be put in .pre-commit-config.yaml to use xenon:
```
  # monitor code’s complexity
  - repo: https://github.com/rubik/xenon
    rev: v0.9.0
    hooks:
      - id: xenon
        args: [ --max-absolute B, --max-modules A, --max-average A ]
```
Maybe someone will find it useful.
